package com.s3scanner.app

import android.util.Log
import scanner.Scanner // will be generated by gomobile

class S3ScannerWrapper {
    init {
        try {
            System.loadLibrary("s3scanner")
        } catch (e: Exception) {
            Log.e("S3Scanner", "Failed to load native library", e)
            throw S3ScannerException("Failed to initialize scanner", e)
        }
    }

    fun scanBucket(bucketName: String): String {
        return Scanner.scanBucket(bucketName)
    }
    
    fun isValidBucketName(bucketName: String): Boolean {
        return Scanner.isValidBucketName(bucketName)
    }
}
